//> using scala 3.6.4
//> using dep org.typelevel::cats-effect:3.7.0
//> using dep com.monovore::decline:2.6.2
//> using dep com.monovore::decline-effect:2.6.2
//> using dep com.augustnagro::magnum:1.3.1
//> using dep org.xerial:sqlite-jdbc:3.53.1.0
//> using dep io.circe::circe-core:0.14.15
//> using dep io.circe::circe-parser:0.14.15
//> using dep io.circe::circe-generic:0.14.15
//> using dep com.lihaoyi::os-lib:0.11.8
//> using dep com.outr::scribe:3.19.0
//> using dep com.outr::scribe-cats:3.19.0
